### ISSUE TITLE
[BUG] 2.84.0-preview.2 lib load regression (preview.1 is ok)

### ISSUE THREAD

**Issue by AndersMad** [mono/SkiaSharp#1513]
**Description**

**Unable to load library 'libSkiaSharp'** - worked in 2.84.0-preview.1 (prior)

Stack trace:
```
SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName)
System.Lazy`1.CreateValue()
System.Lazy`1.LazyInitValue()
SkiaSharp.SkiaApi.sk_managedstream_set_procs(SKManagedStreamDelegates procs)
SkiaSharp.SKAbstractManagedStream..cctor()
```

**Basic Information**

- Version with issue: 2.84.0-preview.2
- Last known good version:  2.84.0-preview.1
- IDE:  Visual Studio 2019
- Platform Target Frameworks: .NETFramework 4.8

**Comment by mattleibow** [comment]
I am trying to get a fix for 84 out. But for some reason VS can no longer build skia! Some update broke it and it can't find headers.

As soon as I get some to, I can release. There is a big bunch of fixes waiting. It is Just the windows builds! 😭

**Comment by MartinZikmund** [comment]
@mattleibow I am getting the following warning when building macOS target, is it the same problem?

```
MSB3341	Could not resolve reference 
"C:\Users\Martin\.nuget\packages\skiasharp\2.84.0-preview.4\
buildTransitive\xamarinmac2.0\..\..\runtimes\osx\native\libSkiaSharp.dylib". 
If this reference is required by your code, you may get compilation errors
```

**Comment by AndersMad** [comment]
FYI: I closed this one yesterday as preview.4 worked - but it turned out that v4 had another issue (#1551)  - I then returned to v1 but got the above error.. Back and forth - it turned out that only v2 is the one working for me now - but that's the one I reported not working here (lib load).. So - I'm a bit confused now - maybe its a file lock / vs.net issue and not a Skia issue.

**Comment by AndersMad** [comment]
@mattleibow Did you take preview v3 offline? That seems to be the "only one working" afaik. This DLL loading issue seems to happen randomly on v1 on running servers and preview > v1 has this one #1551 - so sorry to bother you - but maybe you got a ca. ETA on a v5 possible? Thanks :)
